/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifrn.pds.apresentacao;


import br.edu.ifrn.pds.ws.Filme;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 20201114010026
 */
public class FilmesFrame extends javax.swing.JFrame {

    /**
     * Creates new form FilmesFrame
     */
    public FilmesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        avaliacaoTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        duracaoTextField = new javax.swing.JTextField();
        anoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BuscarUmBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filmesTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        salvarBtn = new javax.swing.JButton();
        apagarBtn = new javax.swing.JButton();
        listarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 232, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Avaliação do filme:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID do filme:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Titulo do filme:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Duração do filme:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ano de lançamento:");

        avaliacaoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        tituloTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        duracaoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        anoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        anoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/pds/apresentacao/BaldeDePipoca-1.png.png"))); // NOI18N

        BuscarUmBtn.setBackground(new java.awt.Color(236, 103, 103));
        BuscarUmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscarUmBtn.setText("Buscar por um filme específico");
        BuscarUmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUmBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(236, 103, 103));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filmesTextArea.setEditable(false);
        filmesTextArea.setColumns(20);
        filmesTextArea.setRows(5);
        filmesTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(filmesTextArea);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrn/pds/apresentacao/JuvamMOvies.png"))); // NOI18N
        jLabel1.setToolTipText("");

        salvarBtn.setBackground(new java.awt.Color(238, 232, 192));
        salvarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        apagarBtn.setBackground(new java.awt.Color(238, 232, 192));
        apagarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apagarBtn.setText("Apagar filme");
        apagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarBtnActionPerformed(evt);
            }
        });

        listarBtn.setBackground(new java.awt.Color(238, 232, 192));
        listarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listarBtn.setText("Listar todos");
        listarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBtnActionPerformed(evt);
            }
        });

        editarBtn.setBackground(new java.awt.Color(238, 232, 192));
        editarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salvarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apagarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBtn)
                    .addComponent(apagarBtn))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarBtn)
                    .addComponent(editarBtn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avaliacaoTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tituloTextField))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(duracaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BuscarUmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(duracaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BuscarUmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBtnActionPerformed
        List<Filme> filmes = listarTodosOsFilmes();

        if (!filmesTextArea.getText().equals("")) {
            filmesTextArea.setText("");
        }
        for (Filme f : filmes) {
            filmesTextArea.append(" ID: "+ f.getId() +"\n Título: "+ f.getTitulo() +
            "\n Ano de lançamento: " + f.getAnoLancamento()+ "\n Avaliação dos críticos: " +
            f.getAvaliacao() + "\n Duração: " +
            f.getDuracao() + "\n");
            filmesTextArea.append("\n");
        }
    }//GEN-LAST:event_listarBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        if (!idTextField.getText().equals("") && !tituloTextField.getText().equals("")
                && !duracaoTextField.getText().equals("") && !anoTextField.getText().equals("")
                && !avaliacaoTextField.getText().equals("")) {
            String idTxt = idTextField.getText();//Pegando o texto da interface gráfica.
            int id = Integer.parseInt(idTxt);
            String titulo = tituloTextField.getText();
            String duracaoTxt = duracaoTextField.getText();
            double duracao = Double.parseDouble(duracaoTxt);
            String anoTxt = anoTextField.getText();//Pegando o texto da interface gráfica.
            int ano = Integer.parseInt(anoTxt);
            String avaliacaoTxt = avaliacaoTextField.getText();
            double avaliacao = Double.parseDouble(avaliacaoTxt);

            Filme obj = new Filme();
            obj.setId(id);
            obj.setTitulo(titulo);
            obj.setDuracao(duracao);
            obj.setAnoLancamento(ano);
            obj.setAvaliacao(avaliacao);

            boolean resultado = alterarFilme(obj);
            if (resultado) {
                JOptionPane.showMessageDialog(rootPane, "Filme atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Filme não atualizado...");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite todas as características para atualizar o filme!");

        }


    }//GEN-LAST:event_editarBtnActionPerformed

    private void apagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarBtnActionPerformed
// TODO add your handling code here:
        if (!idTextField.getText().equals("")) {
            String idTxt = idTextField.getText();
            int id = Integer.parseInt(idTxt);
            boolean resultado = deletarFilme(id);
            if (resultado) {
                JOptionPane.showMessageDialog(rootPane, "Filme apagado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Filme não removido...");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite um ID de filme válido!");

        }    }//GEN-LAST:event_apagarBtnActionPerformed

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        if (!idTextField.getText().equals("") && !tituloTextField.getText().equals("")
                && !duracaoTextField.getText().equals("") && !anoTextField.getText().equals("")
                && !avaliacaoTextField.getText().equals("")) {
            String idTxt = idTextField.getText();//Pegando o texto da interface gráfica.
            int id = Integer.parseInt(idTxt);
            String titulo = tituloTextField.getText();
            String duracaoTxt = duracaoTextField.getText();
            double duracao = Double.parseDouble(duracaoTxt);
            String anoTxt = anoTextField.getText();//Pegando o texto da interface gráfica.
            int ano = Integer.parseInt(anoTxt);
            String avaliacaoTxt = avaliacaoTextField.getText();
            double avaliacao = Double.parseDouble(avaliacaoTxt);

            Filme obj = new Filme();
            obj.setId(id);
            obj.setTitulo(titulo);
            obj.setDuracao(duracao);
            obj.setAnoLancamento(ano);
            obj.setAvaliacao(avaliacao);

            boolean resultado = inserirFilme(obj);
            if (resultado) {
                JOptionPane.showMessageDialog(rootPane, "Filme cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Filme não cadastrado...");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite todas as características do filme.");

        }


    }//GEN-LAST:event_salvarBtnActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void anoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoTextFieldActionPerformed

    private void BuscarUmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUmBtnActionPerformed
        String nome = tituloTextField.getText();

        Filme filme = buscarFilme(nome);
        if (!filmesTextArea.getText().equals("")) {
            filmesTextArea.setText("");
        } else {
            if (verificarExistencia(nome)) {
                filmesTextArea.append(filme.getId() +"\n"+ filme.getTitulo()+ "\n" + 
            filme.getAnoLancamento()+ "\n" + filme.getAvaliacao() + "\n" +
            filme.getDuracao());
                filmesTextArea.append("\n");
            } else if (!verificarExistencia(nome)) {
                JOptionPane.showMessageDialog(rootPane, "Filme não encontrado...");
            }

        }


    }//GEN-LAST:event_BuscarUmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarUmBtn;
    private javax.swing.JTextField anoTextField;
    private javax.swing.JButton apagarBtn;
    private javax.swing.JTextField avaliacaoTextField;
    private javax.swing.JTextField duracaoTextField;
    private javax.swing.JButton editarBtn;
    private javax.swing.JTextArea filmesTextArea;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarBtn;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables

    private static boolean alterarFilme(br.edu.ifrn.pds.ws.Filme objFilme) {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.alterarFilme(objFilme);
    }

    private static Filme buscarFilme(java.lang.String nomeFilme) {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.buscarFilme(nomeFilme);
    }

    private static boolean deletarFilme(int idFilme) {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.deletarFilme(idFilme);
    }

    private static boolean inserirFilme(br.edu.ifrn.pds.ws.Filme objFilme) {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.inserirFilme(objFilme);
    }

    private static java.util.List<br.edu.ifrn.pds.ws.Filme> listarTodosOsFilmes() {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.listarTodosOsFilmes();
    }

    private static boolean verificarExistencia(java.lang.String nomeFilme) {
        br.edu.ifrn.pds.ws.FilmesWS_Service service = new br.edu.ifrn.pds.ws.FilmesWS_Service();
        br.edu.ifrn.pds.ws.FilmesWS port = service.getFilmesWSPort();
        return port.verificarExistencia(nomeFilme);
    }
}
